version: "3.8"

services:
  kafka:
    image: confluentinc/cp-kafka:7.8.3
    container_name: kafka
    environment:
      - KAFKA_KRAFT_MODE=true
      - CLUSTER_ID=1L6g7nGhU-eAKfL--X25wo
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_LOG_DIRS=/var/lib/kafka/data
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    ports:
      - "9092:9092"
    volumes:
      - kafka_kraft:/var/lib/kafka/data
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092 >/dev/null 2>&1"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 20s
    networks:
      - sensor-net

  producer-a:
    image: sensor-producer
    container_name: producer-a
    environment:
      - PRODUCER=producer_A.py
      - ROW_LIMIT=4000
      - KAFKA_BROKER=kafka:9092
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - sensor-net

  producer-b:
    image: sensor-producer
    container_name: producer-b
    environment:
      - PRODUCER=producer_B.py
      - ROW_LIMIT=4000
      - KAFKA_BROKER=kafka:9092
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - sensor-net

  producer-c:
    image: sensor-producer
    container_name: producer-c
    environment:
      - PRODUCER=producer_C.py
      - ROW_LIMIT=4000
      - KAFKA_BROKER=kafka:9092
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - sensor-net

  clickhouse-server:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=sensor
      - CLICKHOUSE_PASSWORD=sensorpass
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ports:
      - "8123:8123" # HTTP interface
      - "9000:9000" # Native TCP interface
    networks:
      - sensor-net
    volumes:
      - ./clickhouse_setup:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    container_name: consumer
    environment:
      - KAFKA_BROKER=kafka:9092
      - CLICKHOUSE_HOST=clickhouse-server
      - CLICKHOUSE_USER=sensor
      - CLICKHOUSE_PASSWORD=sensorpass
      - CLICKHOUSE_DB=default
      - KAFKA_TOPIC=sensor_data
      - BATCH_SIZE=100
      - FLUSH_INTERVAL_SEC=2.0
    depends_on:
      kafka:
        condition: service_started
      clickhouse-server:
        condition: service_healthy
    networks:
      - sensor-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-changeMeStrong!}
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      clickhouse-server:
        condition: service_healthy
    networks:
      - sensor-net

networks:
  sensor-net:
    driver: bridge

volumes:
  kafka_kraft: