version: "3.8"

services:
  kafka:
    image: confluentinc/cp-kafka:7.8.3
    container_name: kafka
    environment:
      - KAFKA_KRAFT_MODE=true
      - CLUSTER_ID=1L6g7nGhU-eAKfL--X25wo
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_LOG_DIRS=/var/lib/kafka/data
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    ports:
      - "9092:9092"
    volumes:
      - kafka_kraft:/var/lib/kafka/data
    networks:
      - sensor-net

  producer-a:
    image: sensor-producer
    container_name: producer-a
    environment:
      - PRODUCER=producer_A.py
      - ROW_LIMIT=4000
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - kafka
    networks:
      - sensor-net

  producer-b:
    image: sensor-producer
    container_name: producer-b
    environment:
      - PRODUCER=producer_B.py
      - ROW_LIMIT=4000
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - kafka
    networks:
      - sensor-net

  producer-c:
    image: sensor-producer
    container_name: producer-c
    environment:
      - PRODUCER=producer_C.py
      - ROW_LIMIT=4000
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - kafka
    networks:
      - sensor-net

networks:
  sensor-net:
    driver: bridge

volumes:
  kafka_kraft: